# Generated by Django 5.2.1 on 2025-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
