# Generated by Django 5.2.1 on 2025-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0003_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DRIVER', 'Driver'), ('ELECTICAL_MAINTENANCE_TEAM', 'Electrical_Maintenance_Team'), ('MECHANICAL_MAINTENANCE_TEAM', 'Mechanical_Maintenance_Team'), ('EMERGENCY_RESPONSE_TEAM', 'Emergency_Response_Team'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
