# Generated by Django 5.2.1 on 2025-08-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['-timestamp']},
        ),
    ]
