# Generated by Django 5.2.1 on 2025-10-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0005_alter_userlocation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotiveSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locomotive', models.CharField(blank=True, max_length=200, null=True)),
                ('loc_type', models.CharField(blank=True, max_length=200, null=True)),
                ('loc_class', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_supply', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_in_tons', models.CharField(blank=True, max_length=100, null=True)),
                ('distributed_power', models.CharField(blank=True, max_length=200, null=True)),
                ('tractive_effort', models.CharField(blank=True, max_length=200, null=True)),
                ('truck_circuit_spec', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
