# Generated by Django 5.2.1 on 2025-10-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0006_locomotivespec'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cargo_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('special_handling', models.CharField(blank=True, max_length=400, null=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WheelsetSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wheel_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('diameter_differentials', models.CharField(blank=True, max_length=200, null=True)),
                ('symmetry', models.CharField(blank=True, max_length=200, null=True)),
                ('radial_run_out', models.CharField(blank=True, max_length=200, null=True)),
                ('axial_run_out', models.CharField(blank=True, max_length=200, null=True)),
                ('witness_marks', models.CharField(blank=True, max_length=200, null=True)),
                ('surface_roughness', models.CharField(blank=True, max_length=200, null=True)),
                ('stenciling', models.CharField(blank=True, max_length=200, null=True)),
                ('main_machine_diameter', models.CharField(blank=True, max_length=200, null=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
