# Generated by Django 5.2.1 on 2025-10-07 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0007_cargospec_wheelsetspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePreferenceSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_route_corridor', models.CharField(blank=True, max_length=300, null=True)),
                ('transshipment_required', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_node', models.CharField(blank=True, max_length=300, null=True)),
                ('receiving_facility', models.CharField(blank=True, max_length=300, null=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
