# Generated by Django 5.2.1 on 2025-10-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0008_routepreferencespec'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotiveAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transnet_mobility.locomotivespec')),
            ],
            options={
                'unique_together': {('locomotive', 'driver')},
            },
        ),
    ]
