# Generated by Django 5.2.1 on 2025-10-07 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0009_locomotiveassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_fuel_consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_cost_per_litre', models.CharField(blank=True, max_length=100, null=True)),
                ('average_load_per_trip', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
