# Generated by Django 5.2.1 on 2025-11-11 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0010_fuelspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargospec',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_entries', to='transnet_mobility.locomotivespec'),
        ),
        migrations.AddField(
            model_name='fuelspec',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='transnet_mobility.locomotivespec'),
        ),
        migrations.AddField(
            model_name='routepreferencespec',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_preference_entries', to='transnet_mobility.locomotivespec'),
        ),
        migrations.AddField(
            model_name='wheelsetspec',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheelset_entries', to='transnet_mobility.locomotivespec'),
        ),
    ]
