# Generated by Django 5.2.1 on 2025-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0012_driverrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_requests/'),
        ),
    ]
