# Generated by Django 5.2.1 on 2025-11-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0013_alter_driverrequest_captured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DRIVER', 'Driver'), ('ELECTRICAL_MAINTENANCE_TEAM', 'Electrical_Maintenance_Team'), ('MECHANICAL_MAINTENANCE_TEAM', 'Mechanical_Maintenance_Team'), ('EMERGENCY_RESPONSE_TEAM', 'Emergency_Response_Team'), ('SECURITY_TEAM', 'Security_Team'), ('MEDICAL_TEAM', 'Medical_Team'), ('TOWING_SERVICE', 'Towing_Service'), ('OTHER', 'Other')], default='OTHER', max_length=55),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DRIVER', 'Driver'), ('ELECTRICAL_MAINTENANCE_TEAM', 'Electrical_Maintenance_Team'), ('MECHANICAL_MAINTENANCE_TEAM', 'Mechanical_Maintenance_Team'), ('EMERGENCY_RESPONSE_TEAM', 'Emergency_Response_Team'), ('SECURITY_TEAM', 'Security_Team'), ('MEDICAL_TEAM', 'Medical_Team'), ('TOWING_SERVICE', 'Towing_Service'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_team', models.CharField(max_length=100)),
                ('assigned_personnel', models.TextField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_made', to=settings.AUTH_USER_MODEL)),
                ('driver_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_logs', to='transnet_mobility.driverrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('dispatch_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transnet_mobility.dispatchlog')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
