# Generated by Django 5.2 on 2025-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0014_alter_customuser_account_type_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargospec',
            name='maintenance_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='OPERATIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='locomotivespec',
            name='maintenance_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='OPERATIONAL', max_length=50),
        ),
    ]
