# Generated by Django 5.2 on 2025-11-11 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0016_driverassignmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargospec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargospec',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('IN_MAINTENANCE', 'In Maintenance'), ('READY_FOR_ACTIVATION', 'Ready for Activation')], default='AVAILABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='locomotivespec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locomotivespec',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('IN_MAINTENANCE', 'In Maintenance'), ('READY_FOR_ACTIVATION', 'Ready for Activation')], default='AVAILABLE', max_length=50),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('LOCOMOTIVE', 'Locomotive'), ('CARGO', 'Cargo')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for maintenance')),
                ('scheduled_date', models.DateTimeField(help_text='When maintenance was scheduled')),
                ('expected_completion_date', models.DateTimeField(help_text='Expected completion date')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('READY_FOR_ACTIVATION', 'Ready for Activation'), ('ACTIVATED', 'Activated')], default='SCHEDULED', max_length=30)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_maintenance', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='transnet_mobility.cargospec')),
                ('locomotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='transnet_mobility.locomotivespec')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStatusUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('update_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='transnet_mobility.maintenanceschedule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
