# Generated by Django 5.2 on 2025-11-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0017_cargospec_is_active_cargospec_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagonSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wagon_number', models.CharField(help_text='Unique wagon identifier', max_length=100, unique=True)),
                ('wagon_type', models.CharField(choices=[('BOX', 'Box Wagon'), ('FLAT', 'Flat Wagon'), ('HOPPER', 'Hopper Wagon'), ('TANK', 'Tank Wagon'), ('REFRIGERATED', 'Refrigerated Wagon'), ('AUTO_CARRIER', 'Auto Carrier'), ('TIPPLER', 'Tippler Wagon')], default='BOX', max_length=50)),
                ('length_over_buffers', models.DecimalField(blank=True, decimal_places=2, help_text='Length in meters (10-25m)', max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Width in meters (2.8-3.2m)', max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters (3.8-4.2m)', max_digits=4, null=True)),
                ('track_gauge', models.CharField(choices=[('1435', '1,435 mm (Standard Gauge)'), ('1067', '1,067 mm (Cape Gauge)')], default='1067', help_text='Track gauge in mm', max_length=10)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Empty weight in tonnes (15-30t)', max_digits=6, null=True)),
                ('payload_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cargo weight in tonnes (40-80t)', max_digits=6, null=True)),
                ('gross_laden_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Tare + payload in tonnes (60-100t)', max_digits=6, null=True)),
                ('axle_load', models.DecimalField(blank=True, decimal_places=2, help_text='Load per axle in tonnes (16-25t)', max_digits=5, null=True)),
                ('maximum_speed', models.IntegerField(blank=True, help_text='Maximum speed in km/h (80-120 km/h)', null=True)),
                ('braking_system', models.CharField(choices=[('UIC', 'UIC Standard Air Brake'), ('AAR', 'AAR Standard Air Brake')], default='UIC', max_length=50)),
                ('coupling_type', models.CharField(choices=[('AAR', 'AAR Knuckle Coupler'), ('SA3', 'SA3 Automatic Coupler')], default='SA3', max_length=50)),
                ('buffer_drawgear_capacity', models.IntegerField(blank=True, help_text='Load capacity in kN (850-1000 kN)', null=True)),
                ('body_material', models.CharField(blank=True, help_text='e.g., High-strength steel (Corten)', max_length=200, null=True)),
                ('frame_construction', models.CharField(blank=True, help_text='e.g., Welded steel underframe', max_length=200, null=True)),
                ('suspension_system', models.CharField(choices=[('COIL', 'Coil Spring Bogies'), ('LEAF', 'Leaf Spring Bogies')], default='COIL', max_length=50)),
                ('bogie_type', models.CharField(choices=[('TWO_AXLE', 'Two-Axle Bogies'), ('FOUR_AXLE', 'Four-Axle Bogies')], default='TWO_AXLE', max_length=50)),
                ('floor_type', models.CharField(blank=True, help_text='e.g., Steel plate, wooden deck', max_length=200, null=True)),
                ('special_features', models.TextField(blank=True, help_text='Type-specific features (e.g., discharge gates, cooling unit)', null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('IN_MAINTENANCE', 'In Maintenance'), ('READY_FOR_ACTIVATION', 'Ready for Activation')], default='AVAILABLE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('survey_raw', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
