# Generated by Django 5.2 on 2025-11-13 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0018_wagonspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotiveWagonAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagon_assignments', to='transnet_mobility.locomotivespec')),
                ('wagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locomotive_assignments', to='transnet_mobility.wagonspec')),
            ],
            options={
                'unique_together': {('locomotive', 'wagon')},
            },
        ),
    ]
