# Generated by Django 5.2 on 2025-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0019_locomotivewagonassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagonspec',
            name='is_assigned',
            field=models.BooleanField(default=False, help_text='True if wagon is currently assigned to a locomotive'),
        ),
    ]
