# Generated by Django 5.2 on 2025-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0020_wagonspec_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotivespec',
            name='maintenance_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('WRITTEN_OFF', 'Written Off')], default='OPERATIONAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='locomotivespec',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('IN_MAINTENANCE', 'In Maintenance'), ('READY_FOR_ACTIVATION', 'Ready for Activation'), ('WRITTEN_OFF', 'Written Off')], default='AVAILABLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='wagonspec',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('IN_MAINTENANCE', 'In Maintenance'), ('READY_FOR_ACTIVATION', 'Ready for Activation'), ('WRITTEN_OFF', 'Written Off')], default='AVAILABLE', max_length=50),
        ),
    ]
