# Generated by Django 5.2 on 2025-11-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0021_alter_locomotivespec_maintenance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_requests', to='transnet_mobility.locomotivespec'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical - Duplicate Request')], default='NORMAL', max_length=20),
        ),
    ]
