# Generated by Django 5.2 on 2025-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0022_driverrequest_locomotive_driverrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequest',
            name='incident_category',
            field=models.CharField(choices=[('CRIME', 'Crime Related'), ('SAFETY', 'Safety Issue'), ('MECHANICAL', 'Mechanical'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
