# Generated by Django 5.2 on 2025-11-13 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0023_driverrequest_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='transnet_mobility.wagonspec'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='item_type',
            field=models.CharField(choices=[('LOCOMOTIVE', 'Locomotive'), ('CARGO', 'Cargo'), ('WAGON', 'Wagon')], max_length=20),
        ),
    ]
