# Generated by Django 5.2 on 2025-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0024_maintenanceschedule_wagon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargospec',
            name='additional_specs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='locomotivespec',
            name='additional_specs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='wheelsetspec',
            name='additional_specs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
