# Generated by Django 5.2 on 2025-11-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0025_cargospec_additional_specs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargospec',
            name='locomotive',
        ),
        migrations.AddField(
            model_name='cargospec',
            name='cargo_weight_tons',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cargo weight in tonnes', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cargospec',
            name='wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_entries', to='transnet_mobility.wagonspec'),
        ),
        migrations.AddField(
            model_name='wagonspec',
            name='additional_specs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='wagonspec',
            name='compatible_cargo_types',
            field=models.JSONField(blank=True, default=list, help_text='List of cargo types compatible with this wagon type', null=True),
        ),
        migrations.AddField(
            model_name='wagonspec',
            name='current_cargo',
            field=models.OneToOneField(blank=True, help_text='Current cargo assigned to this wagon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wagon', to='transnet_mobility.cargospec'),
        ),
    ]
