# Generated by Django 5.2 on 2025-11-15 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0026_remove_cargospec_locomotive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_group_message', models.BooleanField(default=False)),
                ('target_role', models.CharField(blank=True, choices=[('ALL', 'All Users'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DRIVER', 'Driver'), ('ELECTRICAL_MAINTENANCE_TEAM', 'Electrical Maintenance Team'), ('MECHANICAL_MAINTENANCE_TEAM', 'Mechanical Maintenance Team'), ('EMERGENCY_RESPONSE_TEAM', 'Emergency Response Team'), ('SECURITY_TEAM', 'Security Team'), ('MEDICAL_TEAM', 'Medical Team'), ('TOWING_SERVICE', 'Towing Service')], help_text='If group message, specify target role', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='transnet_mobility.privatemessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_by_recipient', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='transnet_mobility.privatemessage')),
            ],
            options={
                'ordering': ['-message__created_at'],
                'unique_together': {('message', 'recipient')},
            },
        ),
    ]
