# Generated by Django 5.2 on 2025-11-15 16:45

import django.db.models.deletion
import transnet_mobility.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0027_privatemessage_messagerecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(default=transnet_mobility.models.generate_uuid, max_length=100, unique=True)),
                ('optimization_type', models.CharField(choices=[('ROUTE_OPTIMIZATION', 'Route Optimization'), ('LOAD_BALANCING', 'Load Balancing'), ('FUEL_EFFICIENCY', 'Fuel Efficiency'), ('MAINTENANCE_SCHEDULING', 'Maintenance Scheduling'), ('WAGON_ALLOCATION', 'Wagon Allocation'), ('LOCOMOTIVE_ASSIGNMENT', 'Locomotive Assignment'), ('FULL_SYSTEM', 'Full System Optimization')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('request_payload', models.JSONField(help_text='Data sent to optimizer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('external_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('optimizer_endpoint', models.URLField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimizer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('REQUEST', 'Request Sent'), ('RESPONSE', 'Response Received'), ('ERROR', 'Error'), ('INFO', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('optimizer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transnet_mobility.optimizerrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OptimizerResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('expected_improvement', models.JSONField(blank=True, help_text='Expected improvements (e.g., fuel savings, time reduction)', null=True)),
                ('current_metrics', models.JSONField(blank=True, help_text='Current performance metrics', null=True)),
                ('projected_metrics', models.JSONField(blank=True, help_text='Projected performance after optimization', null=True)),
                ('implementation_steps', models.JSONField(blank=True, help_text='Steps to implement the suggestion', null=True)),
                ('implementation_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented'), ('PARTIALLY_IMPLEMENTED', 'Partially Implemented')], default='PENDING_REVIEW', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(help_text='Complete response from optimizer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optimizer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='transnet_mobility.optimizerrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='optimizerrequest',
            index=models.Index(fields=['request_id'], name='transnet_mo_request_d20a49_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerrequest',
            index=models.Index(fields=['status'], name='transnet_mo_status_ff0ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerrequest',
            index=models.Index(fields=['created_at'], name='transnet_mo_created_9f1a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerresponse',
            index=models.Index(fields=['implementation_status'], name='transnet_mo_impleme_b37b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizerresponse',
            index=models.Index(fields=['priority'], name='transnet_mo_priorit_29fb25_idx'),
        ),
    ]
