# Generated by Django 5.2.1 on 2025-12-13 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0028_optimizerrequest_optimizationlog_optimizerresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='driver_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('on_leave', 'On Leave'), ('emergency', 'Emergency')], default='available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locomotiveassignment',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locomotiveassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='locomotivespec',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_leave', 'On Leave'), ('emergency', 'Emergency'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='available', max_length=20)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('last_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_schedules', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_schedules', to=settings.AUTH_USER_MODEL)),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_locomotives', to='transnet_mobility.locomotivespec')),
            ],
            options={
                'ordering': ['-date', 'driver'],
                'unique_together': {('driver', 'date', 'shift_type')},
            },
        ),
    ]
