# Generated by Django 5.2.1 on 2026-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0029_customuser_current_location_customuser_driver_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_leave_until',
            field=models.DateField(blank=True, help_text='Date when user should return from leave (auto-reset to available)', null=True),
        ),
    ]
