# Generated by Django 5.2.1 on 2026-01-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0030_customuser_on_leave_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='locomotive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_locomotives', to='transnet_mobility.locomotivespec'),
        ),
    ]
