# Generated by Django 5.2.1 on 2026-01-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0026_schedule_locomotives_manytomany'),
        ('transnet_mobility', '0031_alter_schedule_locomotive'),
    ]

    operations = [
    ]
