from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('home/', views.home, name='edit_user'),
    path('register_user/',views.register_user,name='register_user'),
    path('electrical-maintenance-dashboard/',views.electrical_maintenance_dashboard,name='electrical_maintenance_dashboard'),
    path('mechanical-maintenance-dashboard/',views.mechanical_maintenance_dashboard,name='mechanical_maintenance_dashboard'),
    path('emergency-response-dashboard/',views.emergency_response_dashboard,name='emergency_response_dashboard'),
    path('security-team-dashboard/',views.security_team_dashboard,name='security_team_dashboard'),
    path('medical-team-dashboard/',views.medical_team_dashboard,name='medical_team_dashboard'),
    path('towing-service-dashboard/',views.towing_service_dashboard,name='towing_service_dashboard'),
    path('staff-dashboard/',views.staff_dashboard,name='staff_dashboard'),
    path('locomotive_config/',views.locomotive_config,name='locomotive_config'),
    path('cargo_specs/',views.cargo_specs,name='cargo_specs'),
    path('wagon_specs/',views.wagon_specs,name='wagon_specs'),
    path('wheelset/',views.wheelset,name='wheelset'),
    path('driver_assignment/',views.driver_assignment,name='driver_assignment'),
    path('locomotive_wagon_assignment/',views.locomotive_wagon_assignment,name='locomotive_wagon_assignment'),
    path('all_users/',views.all_users,name='all_users'),
    path('notifications/',views.notifications,name='notifications'),
    path('complete_trip/',views.complete_trip,name='complete_trip'),
    path('trip_data/',views.trip_data,name='trip_data'),
    path('driver_request/',views.driver_request,name='driver_request'),
    path('map_location/',views.map_location,name='map_location'),
    path('map_location_railway/',views.map_location_railway,name='map_location_railway'),
    path('password_reset/',views.password_reset,name='password_reset'),
    path('fuel_matrics/',views.fuel_matrics,name='fuel_matrics'),
    path('load_strategic/',views.load_strategic,name='load_strategic'),
    path('route_and_node_preference/',views.route_and_node_preference,name='route_and_node_preference'),
    path('route_corridor/',views.route_corridor,name='route_corridor'),
    path('profile/',views.profile,name='profile'),
    path('security_guard_report/',views.security_guard_report,name='security_guard_report'),
    path('security_emergency_call/',views.security_emergency_call,name='security_emergency_call'),
    path('security_manager/',views.security_manager,name='security_manager'),
    path('security_supervisor/',views.security_supervisor,name='security_supervisor'),
    path('security_supervisor_call/',views.security_supervisor_call,name='security_supervisor_call'),
    path('logout/',views.logout,name='logout'),
    path("api/update-location/", views.update_location, name="update_location"),
    path('api/locomotive-spec/', views.api_get_locomotive_spec, name='api_get_locomotive_spec'),
    path('api/cargo-spec/', views.api_get_cargo_spec, name='api_get_cargo_spec'),
    path('api/wagon-spec/', views.api_get_wagon_spec, name='api_get_wagon_spec'),
    path('api/wheelset-spec/', views.api_get_wheelset_spec, name='api_get_wheelset_spec'),
    path('api/route-preference-spec/', views.api_get_route_preference_spec, name='api_get_route_preference_spec'),
    path('api/fuel-spec/', views.api_get_fuel_spec, name='api_get_fuel_spec'),
    path('api/count_assigned_drivers/', views.count_assigned_drivers, name='count_assigned_drivers'),
    path('api/emergency-alerts/', views.emergency_alerts, name='emergency_alerts'),
    path('api/maintanance-scheduling/', views.maintanance_scheduling, name='maintanance_scheduling'),
    path('incident-heatmap/', views.incident_heatmap, name='incident_heatmap'),
    path('dispatch-assistance/<int:request_id>/', views.dispatch_assistance, name='dispatch_assistance'),
    path('my-notifications/', views.my_notifications, name='my_notifications'),
    path('dispatch-response/<int:notification_id>/', views.dispatch_response, name='dispatch_response'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('activate-user/<str:user_id>/', views.activate_user, name='activate_user'),
    path('deactivate-user/<str:user_id>/', views.deactivate_user, name='deactivate_user'),
    path('edit-user-admin/<str:user_id>/', views.edit_user_admin, name='edit_user_admin'),
    # Locomotive Management URLs
    path('locomotive-dashboard/', views.locomotive_dashboard, name='locomotive_dashboard'),
    path('schedule-maintenance/', views.schedule_maintenance, name='schedule_maintenance'),
    path('update-maintenance-status/<int:maintenance_id>/', views.update_maintenance_status, name='update_maintenance_status'),
    path('activate-item/<str:item_type>/<int:item_id>/', views.activate_item, name='activate_item'),
    path('maintenance-details/<int:maintenance_id>/', views.maintenance_details, name='maintenance_details'),
    # Mechanical Maintenance URLs
    path('mechanical-maintenance-update/<int:maintenance_id>/', views.mechanical_maintenance_update, name='mechanical_maintenance_update'),
    # Write-off and Delete URLs
    path('write-off-locomotive/<int:loco_id>/', views.write_off_locomotive, name='write_off_locomotive'),
    path('delete-locomotive/<int:loco_id>/', views.delete_locomotive, name='delete_locomotive'),
    path('write-off-wagon/<int:wagon_id>/', views.write_off_wagon, name='write_off_wagon'),
    path('delete-wagon/<int:wagon_id>/', views.delete_wagon, name='delete_wagon'),
    # Wagon Management URLs
    path('wagon-dashboard/', views.wagon_dashboard, name='wagon_dashboard'),
    path('schedule-wagon-maintenance/', views.schedule_wagon_maintenance, name='schedule_wagon_maintenance'),
    path('update-wagon-maintenance-status/<int:maintenance_id>/', views.update_wagon_maintenance_status, name='update_wagon_maintenance_status'),
    path('activate-wagon/<int:wagon_id>/', views.activate_wagon, name='activate_wagon'),
    path('wagon-maintenance-details/<int:maintenance_id>/', views.wagon_maintenance_details, name='wagon_maintenance_details'),
    # Private Messaging URLs
    path('api/search-users/', views.search_users, name='search_users'),
    path('api/send-message/', views.send_message, name='send_message'),
    path('api/get-messages/', views.get_messages, name='get_messages'),
    path('api/get-sent-messages/', views.get_sent_messages, name='get_sent_messages'),
    path('api/mark-message-read/<int:recipient_id>/', views.mark_message_read, name='mark_message_read'),
    path('api/delete-message/<int:recipient_id>/', views.delete_message, name='delete_message'),
    
    # Optimizer API URLs
    path('api/optimizer/request/', views.request_optimization, name='request_optimization'),
    path('api/optimizer/results/', views.receive_optimization_results, name='receive_optimization_results'),
    path('api/optimizer/suggestions/', views.get_optimization_suggestions, name='get_optimization_suggestions'),
    path('api/optimizer/suggestions/<int:suggestion_id>/update/', views.update_suggestion_status, name='update_suggestion_status'),
    path('optimization-dashboard/', views.optimization_dashboard, name='optimization_dashboard'),
]